---
- name: prepare installation
  hosts: OSEv3
  
  tasks:
   - name: install NetworkManager
     yum: name=NetworkManager state=latest
   - name: run NetworkManager
     service: name=NetworkManager state=started

- include: openshift-ansible/playbooks/byo/config.yml

- name: Install fabric8
  vars:
   - gofabric8version: 0.4.31
  hosts: masters
  tasks:
   - name: download gofabric8
     unarchive: src=https://github.com/fabric8io/gofabric8/releases/download/v{{gofabric8version}}/gofabric8-{{gofabric8version}}-linux-amd64.tar.gz dest=/usr/bin/ copy=no
   - name: run gofabric8
     shell: "gofabric8 deploy -y --domain={{ openshift_master_default_subdomain }} --app=cd-pipeline"
   - name: run gofabric8 secrets
     shell: "gofabric8 secrets -y"