---
#required: RHEL, ansible>2.1

#- name: Install docker on all nodes
#  vars:
#   - docker_opts: --selinux-enabled -H unix://var/run/docker.sock -H tcp://0.0.0.0:2375 --insecure-registry 172.30.0.0/16
#  hosts: OSEv3
  
#  roles:
#   - angstwad.docker_ubuntu

#we do not need to install docker - it seems like openshift does it on his own.... :(
#- name: Install docker on all nodes
#  vars:
#   - docker_opts: --selinux-enabled -H unix://var/run/docker.sock -H tcp://0.0.0.0:2375 --insecure-registry 172.30.0.0/16
#  hosts: OSEv3
#  
#  tasks:
#   - name: download get docker
#     get_url: url=https://get.docker.com/ dest=/root/getdocker.sh
#   - name: set permissions to exec
#     file: path=/root/getdocker.sh mode=755
#   - name: exec get docker
#     command: sh /root/getdocker.sh
#   - name: Set docker daemon options
#     copy: content="DOCKER_OPTS=\"{{ docker_opts.rstrip('\n') }}\"" dest=/etc/default/docker owner=root group=root mode=0644
#   - name: Start docker daemon
#     service: name=docker state=started

- name: prepare installation
  hosts: OSEv3
  
  tasks:
   - name: install NetworkManager
     yum: name=NetworkManager state=latest
   - name: run NetworkManager
     service: name=NetworkManager state=started

- include: ../openshift-ansible/playbooks/byo/config.yml

- name: Install fabric8
  vars:
   - gofabric8version: 0.4.31
  hosts: masters
  tasks:
   - name: download gofabric8
     unarchive: src=https://github.com/fabric8io/gofabric8/releases/download/v{{gofabric8version}}/gofabric8-{{gofabric8version}}-linux-amd64.tar.gz dest=/usr/bin/ copy=no
   - name: run gofabric8
     shell: "gofabric8 deploy -y --domain={{ openshift_master_default_subdomain }} --app=cd-pipeline"
   - name: run gofabric8 secrets
     shell: "gofabric8 secrets -y"